# Generated by Django 4.1.5 on 2023-03-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('details', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
