# Generated by Django 4.1.5 on 2023-03-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_features_delete_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_features',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='portfolio_pics'),
        ),
    ]
