# Generated by Django 4.1.5 on 2023-04-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(choices=[('25', '25'), ('50', '50'), ('75', '75'), ('100', '100')], default='25', max_length=100)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('message', models.TextField(null=True)),
                ('payment', models.CharField(choices=[('paypal', 'PayPal'), ('payStack', 'PayStack')], default='paypal', max_length=100)),
            ],
        ),
    ]
