# Generated by Django 4.1.5 on 2023-04-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='reason_for_joining',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
